#!/bin/bash

set -e

install_go()
{
    # Taken from Google/golang Dockerfile...
    apt-get update -y && apt-get install --no-install-recommends -y -q curl build-essential \
        ca-certificates git mercurial bzr
    mkdir /goroot && curl https://storage.googleapis.com/golang/go1.3.1.linux-amd64.tar.gz | tar xvzf - -C /goroot --strip-components=1
    echo $PWD
    echo "export GOROOT=\"/goroot\"" > ./build/bootstrap.envs
    echo "export PATH=\"$PATH:/goroot/bin\"" >> ./build/bootstrap.envs
}


mkdir -p ./build

if [ ! $(command -v go) ]; then
    echo "Going to try installing Go..."
    install_go
fi

if [ ! -x "$(which nsenter)" ]; then
    TMP=$(mktemp -d)
    trap "rm -rf $TMP" exit

    cd $TMP
    wget https://github.com/rancherio/agent-binaries/releases/download/v0.1.2/agent-binaries.tar.gz
    tar xzf agent-binaries.tar.gz
    find -type f -name nsenter -exec cp -v {} /usr/local/bin/nsenter \;
    chmod +x /usr/local/bin/nsenter
fi

apt-get update
apt-get install -y uuid-runtime
