#!/bin/bash -e

cd $(dirname $0)/..

if [ -f ./build/bootstrap.envs ];then
    . ./build/bootstrap.envs
fi

export GOPATH=$(pwd)/.Godeps/_workspace:$(pwd)/.gopath

PACKAGE=./.gopath/src/$(<.package)

if [ -L ${PACKAGE} ]; then
    rm ${PACKAGE}
fi

if [ ! -e ${PACKAGE} ]; then
    mkdir -p $(dirname $PACKAGE)
    ln -s $(pwd) $PACKAGE
fi

echo export GOPATH=$GOPATH

mkdir -p bin
GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o bin/host-api
