#!/bin/bash
set -e -x

cd $(dirname $0)/..

if [ -f ./build/bootstrap.envs ];then
    . ./build/bootstrap.envs
fi

go build -ldflags "-linkmode external -extldflags -static -s" -o bin/host-api
cp -f scripts/lib/net-util.sh bin/net-util.sh
