#!/bin/bash

set -e

cd $(dirname $0)/..

if [ -x "$(which wrapdocker)" ]; then
    wrapdocker > /tmp/docker.log 2>&1
    docker ps -q
fi

if [ ! -x "$(which net-util.sh)" ]; then
    cp scripts/lib/net-util.sh /usr/local/bin/net-util.sh
    chmod +x /usr/local/bin/net-util.sh
fi

if [[ ! -e /host/proc/ ]]; then
    mkdir -p /host
    ln -s /proc /host/proc
fi

. ./scripts/common_functions

set_project_vars

docker run \
  --volume=/:/rootfs:ro \
  --volume=/var/run:/var/run:rw \
  --volume=/sys:/sys:ro \
  --volume=/var/lib/docker/:/var/lib/docker:ro \
  --publish=8080:8080 \
  --detach=true \
  --name=cadvisor \
  google/cadvisor:latest --logtostderr 

docker run -itd busybox /bin/sh

go test ./...

result=$(find . -name "*.go" | grep -v ./Godeps | xargs gofmt -l)
for i in $result; do
    echo Violates gofmt: $i
done

[ -n "$result" ] && exit 1

echo OK
